version: '2'

services:
  ipfs:
    container_name: ipfs.example.com
    image: ipfs/go-ipfs:v0.18.1
    environment:
      - IPFS_PROFILE=server
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
    restart: unless-stopped
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    networks:
      ecg_network:
        ipv4_address: 172.20.1.6

  client:
    container_name: client.example.com
    image: python:3.9-slim
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../client:/app
      - ./crypto-config:/app/crypto-config
      - ./channel-artifacts:/app/channel-artifacts
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python app/webapp.py"
    depends_on:
      - ipfs
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      ecg_network:
        ipv4_address: 172.20.1.7

volumes:
  ipfs_staging:
  ipfs_data:

networks:
  ecg_network:
    external: true
